CREATE TABLE IF NOT EXISTS local_user_follow_undo (
    id UUID PRIMARY KEY,
    target BIGINT NOT NULL REFERENCES person ON DELETE CASCADE,
    follower BIGINT NOT NULL REFERENCES person ON DELETE CASCADE
);
